config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post '/send_email', to: 'home#send_email'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# app/controllers/home_controller.rb

class HomeController < ApplicationController
  def index
  end

  def send_email
    recipient_email = params[:recipient_email]
    subject = params[:subject]
    recipient_name = params[:recipient_name]

    UserMailer.send_email(recipient_email, subject, recipient_name).deliver_now
    redirect_to root_path, notice: 'Email sent successfully!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->

<h1>Welcome to SimpleEmailApp</h1>

<%= form_tag send_email_path, method: :post do %>
  <div class="form-group">
    <%= label_tag 'recipient_email', 'Recipient Email:' %>
    <%= text_field_tag 'recipient_email', nil, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= label_tag 'subject', 'Subject:' %>
    <%= text_field_tag 'subject', 'Subject of the email', class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= label_tag 'recipient_name', 'Recipient Name:' %>
    <%= text_field_tag 'recipient_name', nil, class: 'form-control', required: true %>
  </div>

  <%= submit_tag 'Send Email', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleEmailApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>